# Generated by Django 2.0.5 on 2018-05-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete='RESTRICT', related_name='comments', to='blog.Post'),
        ),
    ]
